version: 0.2 
 
phases: 
  install: 
    runtime-versions: 
      nodejs: 10 
    commands: 
      - echo install started on `date` 
 
  pre_build: 
    commands: 
      - echo pre_build started on `date` 
      - npm -v 
      - node -v 
      - aws --version 
 
  build: 
    commands: 
      - echo build started on `date` 
      - npm install --production
 
  post_build: 
    commands: 
      - echo post_build started on `date` 
 
artifacts: 
  files: 
    - app.js 
    - bin/**/* 
    - node_modules/**/* 
    - public/**/* 
    - src/**/* 
    - routes/**/* 
    - views/**/* 
    - scripts/**/* 
    - package.json 
    - package-lock.json 
    - appspec.yml 
